<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AcoParametroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('acopio.aco_parametro')->insert([
            [
                "acp_tipo_analisis_id" => 6,
                "acp_tipo_id" => 6,
                "acp_programa_id" => 6,
                "acp_nombre" => "PH",
                "acp_categoria" => "FISICO QUIMICO",
                "acp_descripcion" => "FISICO QUIMICO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 6,
                "acp_limite_aceptable" => 7, 
                "acp_ponderacion" => 15,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [   
                "acp_tipo_analisis_id" => 7,
                "acp_tipo_id" => 7,
                "acp_programa_id" => 6,
                "acp_nombre" => "TEMPERATURA INTERNA",
                "acp_categoria" => "FISICO QUIMICO",
                "acp_descripcion" => "FISICO QUIMICO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 0,
                "acp_limite_aceptable" => 4, 
                "acp_ponderacion" => 10,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 8,
                "acp_tipo_id" => 8,
                "acp_programa_id" => 6,
                "acp_nombre" => "TEMPERATURA EXTERNA",
                "acp_categoria" => "FISICO QUIMICO",
                "acp_descripcion" => "FISICO QUIMICO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 0,
                "acp_limite_aceptable" => 5, 
                "acp_ponderacion" => 5,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 9,
                "acp_tipo_id" => 9,
                "acp_programa_id" => 6,
                "acp_nombre" => "PRESENCIA DE OFF FLAVOR",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "GRADO 0-4 (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 30,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 10,
                "acp_tipo_id" => 10,
                "acp_programa_id" => 6,
                "acp_nombre" => "OLOR",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "CLASIFICACION 0-3  (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 5,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 11,
                "acp_tipo_id" => 11,
                "acp_programa_id" => 6,
                "acp_nombre" => "OJOS",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "CLASIFICACION 0-3  (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 3,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 12,
                "acp_tipo_id" => 12,
                "acp_programa_id" => 6,
                "acp_nombre" => "PIEL",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "CLASIFICACION 0-3  (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 3,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 13,
                "acp_tipo_id" => 13,
                "acp_programa_id" => 6,
                "acp_nombre" => "BRANQUIAS",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "CLASIFICACION 0-3  (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 3,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1
            ],
            [
                "acp_tipo_analisis_id" => 14,
                "acp_tipo_id" => 14,
                "acp_programa_id" => 6,
                "acp_nombre" => "CARNE",
                "acp_categoria" => "CONTROL ORGANOLEPTICO",
                "acp_descripcion" => "CLASIFICACION 0-3 (SI/NO)",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => NULL,
                "acp_limite_aceptable" => NULL, 
                "acp_ponderacion" => 5,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 15,
                "acp_tipo_id" => 15,
                "acp_programa_id" => 6,
                "acp_nombre" => "PESO MUESTRA (kg)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "CORTE LONGITUDINAL",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 1.2,
                "acp_limite_aceptable" => 1.499, 
                "acp_ponderacion" => 10,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 16,
                "acp_tipo_id" => 16,
                "acp_programa_id" => 6,
                "acp_nombre" => "LONGITUD ESTANDAR (cm)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "CORTE LONGITUDINAL",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 30,
                "acp_limite_aceptable" => 39, 
                "acp_ponderacion" => 5,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 17,
                "acp_tipo_id" => 17,
                "acp_programa_id" => 6,
                "acp_nombre" => "LONGITUD TOTAL (cm)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "CORTE LONGITUDINAL",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 33,
                "acp_limite_aceptable" => 44, 
                "acp_ponderacion" => 1,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 18,
                "acp_tipo_id" => 18,
                "acp_programa_id" => 6,
                "acp_nombre" => "PESO MUESTRA (kg)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "FILETE DESESPINADO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 1.5,
                "acp_limite_aceptable" => 2, 
                "acp_ponderacion" => 10,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 19,
                "acp_tipo_id" => 19,
                "acp_programa_id" => 6,
                "acp_nombre" => "LONGITUD ESTANDAR (cm)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "FILETE DESESPINADO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 35,
                "acp_limite_aceptable" => 47, 
                "acp_ponderacion" => 5,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 20,
                "acp_tipo_id" => 20,
                "acp_programa_id" => 6,
                "acp_nombre" => "LONGITUD TOTAL (cm)",
                "acp_categoria" => "BIOMETRIA",
                "acp_descripcion" => "FILETE DESESPINADO",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 36,
                "acp_limite_aceptable" => 55, 
                "acp_ponderacion" => 1,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 21,
                "acp_tipo_id" => 21,
                "acp_programa_id" => 6,
                "acp_nombre" => "PRESENCIA DE ALIMENTO",
                "acp_categoria" => "OTROS",
                "acp_descripcion" => "OTROS",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0.5,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 0,
                "acp_limite_aceptable" => 0.1, 
                "acp_ponderacion" => 4,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            [
                "acp_tipo_analisis_id" => 22,
                "acp_tipo_id" => 22,
                "acp_programa_id" => 6,
                "acp_nombre" => "GRASA VISCERAL <5%",
                "acp_categoria" => "OTROS",
                "acp_descripcion" => "OTROS",
                "acp_valor_min_admisible" => 0,
                "acp_valor_admisible" => 0,
                "acp_valor_base" => 0,
                "acp_valor_base_excedente" => 0,
                "acp_valor_castigo" => 0.5,
                "acp_cantidad_rango" => 0,
                "acp_rendimiento" => 0,
                "acp_limite_tolerancia" => 0,
                "acp_limite_aceptable" => 5, 
                "acp_ponderacion" => 1,               
                "acp_periodo_id" => 0,
                "acp_formula" => 0,
                "acp_usr_registrado" => 1,
            ],
            // //ARROZ
            // [
            //     "acp_tipo_id" => 1,
            //     "acp_programa_id" => 1,
            //     "acp_nombre" => "HUMEDAD",
            //     "acp_categoria" => "HUMEDAD",
            //     "acp_descripcion" => "HUMEDAD",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 18,
            //     "acp_valor_base" => 14,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 2,
            //     "acp_programa_id" => 1,
            //     "acp_nombre" => "IMPUREZA",
            //     "acp_categoria" => "IMPUREZA",
            //     "acp_descripcion" => "IMPUREZA",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 10,
            //     "acp_valor_base" => 1,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 3,
            //     "acp_programa_id" => 1,
            //     "acp_nombre" => "PARTIDO",
            //     "acp_categoria" => "PARTIDO",
            //     "acp_descripcion" => "PARTIDO",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 12,
            //     "acp_valor_base" => 6,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // //
            // [
            //     "acp_tipo_id" => 1,
            //     "acp_programa_id" => 2,
            //     "acp_nombre" => "HUMEDAD",
            //     "acp_categoria" => "HUMEDAD",
            //     "acp_descripcion" => "HUMEDAD",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 18,
            //     "acp_valor_base" => 14,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 2,
            //     "acp_programa_id" => 2,
            //     "acp_nombre" => "IMPUREZA",
            //     "acp_categoria" => "IMPUREZA",
            //     "acp_descripcion" => "IMPUREZA",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 10,
            //     "acp_valor_base" => 1,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 3,
            //     "acp_programa_id" => 2,
            //     "acp_nombre" => "PARTIDO",
            //     "acp_categoria" => "PARTIDO",
            //     "acp_descripcion" => "PARTIDO",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 12,
            //     "acp_valor_base" => 6,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],

            // //
            // [
            //     "acp_tipo_id" => 1,
            //     "acp_programa_id" => 3,
            //     "acp_nombre" => "HUMEDAD",
            //     "acp_categoria" => "HUMEDAD",
            //     "acp_descripcion" => "HUMEDAD",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 18,
            //     "acp_valor_base" => 14,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 2,
            //     "acp_programa_id" => 3,
            //     "acp_nombre" => "IMPUREZA",
            //     "acp_categoria" => "IMPUREZA",
            //     "acp_descripcion" => "IMPUREZA",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 10,
            //     "acp_valor_base" => 1,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 3,
            //     "acp_programa_id" => 3,
            //     "acp_nombre" => "PARTIDO",
            //     "acp_categoria" => "PARTIDO",
            //     "acp_descripcion" => "PARTIDO",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 12,
            //     "acp_valor_base" => 6,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],

            // // 
            // [
            //     "acp_tipo_id" => 1,
            //     "acp_programa_id" => 4,
            //     "acp_nombre" => "HUMEDAD",
            //     "acp_categoria" => "HUMEDAD",
            //     "acp_descripcion" => "HUMEDAD",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 18,
            //     "acp_valor_base" => 14,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 2,
            //     "acp_programa_id" => 4,
            //     "acp_nombre" => "IMPUREZA",
            //     "acp_categoria" => "IMPUREZA",
            //     "acp_descripcion" => "IMPUREZA",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 10,
            //     "acp_valor_base" => 1,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 3,
            //     "acp_programa_id" => 4,
            //     "acp_nombre" => "PARTIDO",
            //     "acp_categoria" => "PARTIDO",
            //     "acp_descripcion" => "PARTIDO",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 12,
            //     "acp_valor_base" => 6,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],

            // //
            // [
            //     "acp_tipo_id" => 1,
            //     "acp_programa_id" => 5,
            //     "acp_nombre" => "HUMEDAD",
            //     "acp_categoria" => "HUMEDAD",
            //     "acp_descripcion" => "HUMEDAD",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 18,
            //     "acp_valor_base" => 14,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,               
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 2,
            //     "acp_programa_id" => 5,
            //     "acp_nombre" => "IMPUREZA",
            //     "acp_categoria" => "IMPUREZA",
            //     "acp_descripcion" => "IMPUREZA",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 10,
            //     "acp_valor_base" => 1,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL, 
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,              
            //     "acp_usr_registrado" => 1,
            // ],
            // [
            //     "acp_tipo_id" => 3,
            //     "acp_programa_id" => 5,
            //     "acp_nombre" => "PARTIDO",
            //     "acp_categoria" => "PARTIDO",
            //     "acp_descripcion" => "PARTIDO",
            //     "acp_valor_min_admisible" => 0,
            //     "acp_valor_admisible" => 12,
            //     "acp_valor_base" => 6,
            //     "acp_valor_base_excedente" => 0,
            //     "acp_valor_castigo" => 1,
            //     "acp_cantidad_rango" => NULL,
            //     "acp_rendimiento" => NULL,
            //     "acp_limite_tolerancia" => NULL,
            //     "acp_limite_aceptable" => NULL, 
            //     "acp_ponderacion" => NULL,
            //     "acp_periodo_id" => 0,
            //     "acp_formula" => 0,
            //     "acp_usr_registrado" => 1,

            // ],
        ]);
    }
}
