<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogoMaterialInsumoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('insumos.catalogo_materiales_insumos')->insert([
            [
                'id' => 518,
                'nombre' => 'CABLE UTP 23 AWG MULTUFILAR CAT 6',
                'descripcion' => 'CABLE UTP 23 AWG MULTUFILAR CAT 6',
                'codigo' => 'SIS116',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 35,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
             [
                'id' => 519,
                'nombre' => 'CABLE UTP 23 AEG SOLIDO CAT-6',
                'descripcion' => 'CABLE UTP 23 AEG SOLIDO CAT-6',
                'codigo' => 'SIS117',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 35,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 616,
                'nombre' => 'ANTENA WIFI EXTERNA 2.46H2 NAR',
                'descripcion' => 'ANTENA WIFI EXTERNA 2.46H2 NAR',
                'codigo' => 'SIS118',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 520,
                'nombre' => 'CAJA DOSABLE (114X70X39)MM',
                'descripcion' => 'CAJA DOSABLE (114X70X39)MM',
                'codigo' => 'SIS119',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 34500,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 521,
                'nombre' => 'CANALETAS PARA CABLE 20X10MM',
                'descripcion' => 'CANALETAS PARA CABLE 20X10MM',
                'codigo' => 'SIS120',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 34500,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 522,
                'nombre' => 'CAPUCHONES (CAJA/BOLSA DE 100 UNID.)',
                'descripcion' => 'CAPUCHONES (CAJA/BOLSA DE 100 UNID.)',
                'codigo' => 'SIS121',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 35,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 34500,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 523,
                'nombre' => 'CEPILLO DE DIENTES',
                'descripcion' => 'CEPILLO DE DIENTES',
                'codigo' => 'SIS122',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 34500,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 524,
                'nombre' => 'CINTA AISLANTE (NEGRO) 19MMX18M',
                'descripcion' => 'CINTA DOBLE CARA VHB 5958 (SIS 123)',
                'codigo' => 'SIS123',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 26,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:01',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 526,
                'nombre' => 'ALICATE DE CORTE (SIS124)',
                'descripcion' => 'ALICATE DE CORTE (SIS124)',
                'codigo' => 'SIS124',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 527,
                'nombre' => 'CAMISAS TIPO COLUMBIA M/L',
                'descripcion' => 'CAMISA TIPO COLUMBIA M/L MANGA LARGA PARA VARON Y MUJER',
                'codigo' => 'CATC001',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 31, 
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 528,
                'nombre' => 'CAMISA TIPO COLUMBIA M/C',
                'descripcion' => 'CAMISA TIPO COLUMBIA M/C MANGA CORTA PARA VARON Y MUJER',
                'codigo' => 'CATC002',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 31,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 529,
                'nombre' => 'FUENTE DE PODER DELL',
                'descripcion' => 'FUENTE DE PODER DELL',
                'codigo' => 'SIS125',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 530,
                'nombre' => 'DESTORNILLADORES DE PRECISION',
                'descripcion' => 'DESTORNILLADORES DE PRECISION IMANTADOS',
                'codigo' => 'SIS126',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 29,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 22,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 531,
                'nombre' => 'SOPLADOR STANDARD',
                'descripcion' => 'SOPLADOR STANDARD DE 700W U 800W',
                'codigo' => 'SIS127',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 37,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 532,
                'nombre' => 'CONECTORES RJ-11',
                'descripcion' => 'CONECTORES RJ-11',
                'codigo' => 'SIS128',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 35,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 533,
                'nombre' => 'SWITCH 8 PUERTOS',
                'descripcion' => 'SWITCH DE 8 PUERTOS',
                'codigo' => 'SIS129',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 534,
                'nombre' => 'BATERIA (2032) 3VCC',
                'descripcion' => 'BATERIA (2032) 3VCC',
                'codigo' => 'SIS130',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 535,
                'nombre' => 'ROLLO DE ALAMBRE DE ESTAÑO',
                'descripcion' => 'ROLLO DE ALAMBRE DE ESTAÑO',
                'codigo' => 'SIS131',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 22,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 536,
                'nombre' => 'ALCOHOL ISOPROPILICO DE (500ML)',
                'descripcion' => 'ALCOHOL ISOPROPILICO DE (500ML)',
                'codigo' => 'SIS132',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 37,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 19,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 537,
                'nombre' => 'HDD SATA PARA NOTEBOOK 1TB',
                'descripcion' => 'HDD SATA PARA NOTEBOOK 1TB',
                'codigo' => 'SIS133',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 538,
                'nombre' => 'HDD SATA PARA PC 1TB',
                'descripcion' => 'HDD SATA PARA PC 1TB',
                'codigo' => 'SIS134',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 539,
                'nombre' => 'LUBRICANTE WD-40 DE (191ML)',
                'descripcion' => 'LUBRICANTE WD-40 DE (191ML)',
                'codigo' => 'SIS135',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 37,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 34100,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 540,
                'nombre' => 'MOUSE OPTICO USB PARA PC',
                'descripcion' => 'MOUSE OPTICO USB PARA PC COMPATIBILIDAD DE SISTEMA: WINDOWS 10/8.1/8/7',
                'codigo' => 'SIS136',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 541,
                'nombre' => 'SUPER PEGAMENTO EN GEL',
                'descripcion' => 'SUPER PEGAMENTO EN GEL',
                'codigo' => 'SIS137',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 542,
                'nombre' => 'CONECTORES RJ-45 CATEGORÍA 6',
                'descripcion' => 'CONECTORES RJ-45 TRANSPARENTES PARA CABLE UTP CATEGORÍA 6',
                'codigo' => 'SIS138',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 35,
                'id_categoria_principal' => 20,
                'id_codigo_partida' => 39700,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 543,
                'nombre' => 'UÑAS GUIADORAS DE PAPEL',
                'descripcion' => 'UÑAS GUIADORAS DE PAPEL',
                'codigo' => 'UGDP001',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 544,
                'nombre' => 'CUCHILLA DE LIMPIEZA',
                'descripcion' => 'CUCHILLA DE LIMPIEZA',
                'codigo' => 'CUL002',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 545,
                'nombre' => 'TERMISTOR',
                'descripcion' => 'TERMISTOR',
                'codigo' => 'TER003',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 546,
                'nombre' => 'FUSIBLE TERMICO',
                'descripcion' => 'FUSIBLE TERMICO',
                'codigo' => 'FTER004',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 547,
                'nombre' => 'IMAGE RUNNER UNIDAD PRIMERY',
                'descripcion' => 'IMAGE RUNNER UNIDAD PRIMERY DE CORONA',
                'codigo' => 'IRUP005',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 548,
                'nombre' => 'IMAGE RUNNER PULLE GEER',
                'descripcion' => 'IMAGE RUNNER PULLE GEER 5065 44J/41 T',
                'codigo' => 'IRPG006',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 549,
                'nombre' => 'IMAGE RUNNER- MAQ. ROLLER',
                'descripcion' => 'IMAGE RUNNER- MAQ. ROLLER',
                'codigo' => 'IRMR007',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 550,
                'nombre' => 'TERMOS WITCH',
                'descripcion' => 'TERMOS WITCH',
                'codigo' => 'TSW008',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 551,
                'nombre' => 'IMAGE RUNNER CLEANIG PAD BLOCK',
                'descripcion' => 'IMAGE RUNNER CLEANIG PAD BLOCK',
                'codigo' => 'IRCP009',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 552,
                'nombre' => 'CLOSCH',
                'descripcion' => 'CLOSCH',
                'codigo' => 'CSH010',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 553,
                'nombre' => 'BARRA DE TEMPERATURA',
                'descripcion' => 'BARRA DE TEMPERATURA',
                'codigo' => 'BDT011',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 554,
                'nombre' => 'READER CONTROLLER PCB ASSEMBLY',
                'descripcion' => 'READER CONTROLLER PCB ASSEMBLY',
                'codigo' => 'RCPA012',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 555,
                'nombre' => 'CCD ASSEMBLY',
                'descripcion' => 'CCD ASSEMBLY',
                'codigo' => 'CCDA013',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 556,
                'nombre' => 'FUSER FILM',
                'descripcion' => 'FUSER FILM',
                'codigo' => 'FUFI014',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 30,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 557,
                'nombre' => 'WINCHA DE 100 METROS',
                'descripcion' => 'WINCHA DE 100 METROS',
                'codigo' => 'WDM001',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 558,
                'nombre' => 'FLEXOMETRO DE 5 METROS',
                'descripcion' => 'FLEXOMETRO DE 5 METROS',
                'codigo' => 'FDM002',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 559,
                'nombre' => 'CALIBRADOR DE PIE DE REY-DIGITAL',
                'descripcion' => 'CALIBRADOR DE PIE DE REY-DIGITAL',
                'codigo' => 'CPRD003',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 560,
                'nombre' => 'NIVEL DE BURBUJAS 45CM',
                'descripcion' => 'NIVEL DE BURBUJAS 45CM',
                'codigo' => 'NDB004',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 561,
                'nombre' => 'TORQUIMETRO',
                'descripcion' => 'TORQUIMETRO',
                'codigo' => 'TQT005',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 23,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 562,
                'nombre' => 'CASCO CLASE \"E\"',
                'descripcion' => 'CASCO CLASE \"E\"',
                'codigo' => 'CCE006',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 563,
                'nombre' => 'MENTONERA PARA CASCO',
                'descripcion' => 'MENTONERA PARA CASCO',
                'codigo' => 'MPC007',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 564,
                'nombre' => 'PROTECTOR AUDITIVO TIPO COPA',
                'descripcion' => 'PROTECTOR AUDITIVO TIPO COPA',
                'codigo' => 'PAC008',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 565,
                'nombre' => 'UNIFORME PANTALON VAQUERO Y CAMISA INDUSTRIAL',
                'descripcion' => 'UNIFORME PANTALON TIPO VAQUERO Y CAMISA INDUSTRIAL',
                'codigo' => 'UPCI009',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 566,
                'nombre' => 'LENTES CONTRA IMPACTO CLAROS',
                'descripcion' => 'LENTES CONTRA IMPACTO CLAROS',
                'codigo' => 'LCIC010',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 567,
                'nombre' => 'LENTES CONTRA IMPACTO OSCUROS',
                'descripcion' => 'LENTES CONTRA IMPACTO OSCUROS',
                'codigo' => 'LCIO011',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 568,
                'nombre' => 'CHALECOS REFLECTIVOS- DELGADO',
                'descripcion' => 'CHALECOS REFLECTIVOS- DELGADO',
                'codigo' => 'CHRD012',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 569,
                'nombre' => 'CHALECOS REFLECTIVOS - GRUESO',
                'descripcion' => 'CHALECOS REFLECTIVOS - GRUESO',
                'codigo' => 'CHRG013',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 570,
                'nombre' => 'GUANTES DIELECTRICOS ',
                'descripcion' => 'GUANTES DIELECTRICOS ',
                'codigo' => 'GUDI014',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 571,
                'nombre' => 'PROTECTOR AUDITIVOS DE SILICONA',
                'descripcion' => 'PROTECTOR AUDITIVOS DE SILICONA',
                'codigo' => 'PADS015',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 572,
                'nombre' => 'SOMBRERO ADOSABLE AL CASCO',
                'descripcion' => 'SOMBRERO ADOSABLE AL CASCO',
                'codigo' => 'SAAC016',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 573,
                'nombre' => 'BOTIQUIN DE PRIMEROS AUXILIOS',
                'descripcion' => 'BOTIQUIN DE PRIMEROS AUXILIOS',
                'codigo' => 'BDPA017',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 32,
                'id_codigo_partida' => 19,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 574,
                'nombre' => 'CARPAS PLÁSTICAS DE 210GRS. 20MT.X 20MT. GAT',
                'descripcion' => 'CARPAS PLÁSTICAS DE 210GRS. 20MT.X 20MT. GAT',
                'codigo' => 'CAP001',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 26,
                'id_codigo_partida' => 16,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 575,
                'nombre' => 'ANILLADORA INDUSTRIAL',
                'descripcion' => 'ANILLADORA INDUSTRIAL',
                'codigo' => 'ANI001',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 14,
                'id_codigo_partida' => 26,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 576,
                'nombre' => 'BATERIA DE 75 AMP. 12U. MOURA',
                'descripcion' => 'BSTERIA DE 75 AMP. 12 U.  MOURA LIBRE MANTENIMIENTO',
                'codigo' => 'BAT03',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 577,
                'nombre' => 'BATERIA DE 150 AMP.MOURA ',
                'descripcion' => 'BATERIAS DE 150 AMP. MOURA LIBRE MANTENIMIENTO',
                'codigo' => 'BAT04',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 578,
                'nombre' => 'BATERIA DE 90 AMP.',
                'descripcion' => 'BATERIAS DE 90 AMP AURA LIBRE MANTENIMUENTO',
                'codigo' => 'BAT 05',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 579,
                'nombre' => 'BATERIAS 100 AMP. MOURA ',
                'descripcion' => 'BATERIA DE 100 AMP. MOURA LIBRE MANTENIMIENTO',
                'codigo' => 'BAT07',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 39800,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 580,
                'nombre' => 'TONER HP 26 A CF 226A IMPRESORA M402,MFP M426',
                'descripcion' => 'TONER HP 26 A CF 226A IMPRESORA M402,MFP M426',
                'codigo' => 'TH 26',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 6,
                'id_codigo_partida' => 26,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 581,
                'nombre' => 'ANILLA P/ENCUADERNAR 12MM BOLSA DE 100 UNIDADES',
                'descripcion' => 'ANILLA P/ENCUADERNAR 12MM BOLSA DE 100 UNIDADES',
                'codigo' => 'AE012',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 14,
                'id_codigo_partida' => 26,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 582,
                'nombre' => 'PAPEL CARTA RECICLADO (FOTOCOPIA) DE 75 GRS.',
                'descripcion' => 'PAPEL CARTA RECICLADO (FOTOCOPIA) DE 75 GRS. TAMAÑO CARTA 21.5X28 CM',
                'codigo' => 'PB014',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 31,
                'id_categoria_principal' => 5,
                'id_codigo_partida' => 14,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,                
            ],
            [
                'id' => 583,
                'nombre' => 'PAPEL OFICIO RECICLADO(FOTOCOPIA) DE 75 GRS ',
                'descripcion' => 'PAPEL OFICIO RECICLADO(FOTOCOPIA) DE 75 GRS   TAMAÑO OFICIO 21,5X33 CM',
                'codigo' => 'PB015',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 31,
                'id_categoria_principal' => 5,
                'id_codigo_partida' => 14,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 584,
                'nombre' => 'LLANTA 295/80 R22.5 DIRECCIONAL',
                'descripcion' => 'LLANTA 295/80 R22.5 DIRECCIONAL',
                'codigo' => 'LLA03',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 34300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 585,
                'nombre' => 'LLANTA 295/80 R22.5 TRACCIONAL',
                'descripcion' => 'LLANTA 295/80 R22.5 TRACCIONAL',
                'codigo' => 'LLA04',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 34300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'cmd_id' => 586,
                'cmd_nombre' => 'LLANTA 245/75 R16 HILUX',
                'cmd_descripcion' => 'LLANTA 245/75 R16 HILUX',
                'cmd_codigo' => 'LLA05',
                'cmd_imagen' => null,
                'cmd_extimagen' => null,
                'cmd_id_unidad_medida' => 27,
                'cmd_id_categoria_principal' => 19,
                'cmd_id_codigo_partida' => 34300,
                'cmd_id_user' => null,
                'cmd_fecha_creacion' => '2023-09-20 17:52:02',
                'cmd_fecha_eliminacion' => null,
            ],
            [
                'id' => 587,
                'nombre' => 'LLANTA 225/75 R16 NISSAN FRONTIER',
                'descripcion' => 'LLANTA 225/75 R16 NISSAN FRONTIER',
                'codigo' => 'LLA06',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 19,
                'id_codigo_partida' => 34300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 588,
                'nombre' => 'CHAMARRA INSTITUCIONAL',
                'descripcion' => 'CHAMARRA INSTITUCIONAL',
                'codigo' => 'CHA03',
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 21,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ],
            [
                'id' => 589,
                'nombre' => 'TONER HP CF 410 A NEGRO PARA IMPRESORA M477',
                'descripcion' => 'TONER HP CF 410 A NEGRO PARA IMPRESORA A COLOR JET PRO MFPM477',
                'codigo' => 'TH027',
                'id_unidad_medida' => 27,
                'imagen' => null,
                'extimagen' => null,
                'id_unidad_medida' => 27,
                'id_categoria_principal' => 21,
                'id_codigo_partida' => 33300,
                'id_user' => null,
                'fecha_creacion' => '2023-09-20 17:52:02',
                'fecha_eliminacion' => null,
            ] 
        ]);
    }
}
