<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedorInsumoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('insumos.proveedores_insumos')->insert([
            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 0,
                "direccion" => 0,
                "NIT" => "7123044",
                "razon_social" => "No Cuenta",
                "informacion_contacto" => 0,
            ],

           

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 4297485,
                "direccion" => "Av. 16 de Julio",
                "NIT" => "7123446",
                "razon_social" => "QSI INDUSTRIAL BOLIVIA S.A",
                "informacion_contacto" => 4297485,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 71523021,
                "direccion" => "ZONA EL ZAPALLAR, EX PREDIOS LA ESMERALDA, MONTEAGUDO_BOLIVIA",
                "NIT" => "4019017",
                "razon_social" => "CIP APÍCOLA MONTEAGUDO",
                "informacion_contacto" => 71523021,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 4523225,
                "direccion" => "Calle Antezana No. 279",
                "NIT" => "1778161",
                "razon_social" => "GEDESA",
                "informacion_contacto" => 4523225,
            ],

            [
                "nombres" => "..",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 4523225,
                "direccion" => "Calle Antezana No. 279",
                "NIT" => "10623795",
                "razon_social" => "GEDESA  LTDA.",
                "informacion_contacto" => 4523225,
            ],

            [
                "nombres" => "..",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 72208094,
                "direccion" => "Av. Simon Lopez No. 585",
                "NIT" => "5001228",
                "razon_social" => "WET CHEMICAL",
                "informacion_contacto" => 72208094,
            ],

            [
                "nombres" => "CAROLINA",
                "apellido_paterno" => "MUKAY",
                "apellido_materno" => "RODRIGUEZ",
                "celular" => 77469035,
                "direccion" => "AV. MAXIMO HENNICKE OFICINA CENTRAL EBA RIBERALTA",
                "NIT" => "4150411",
                "razon_social" => "PLANTA RIBERALTA - MATERIAL DE ESCRITORIO",
                "informacion_contacto" => 8524586,
            ],

            [
                "nombres" => "G",
                "apellido_paterno" => "B",
                "apellido_materno" => "C",
                "celular" => 73968390,
                "direccion" => "Barrio Senac Calle Jose Quintin",
                "NIT" => "5797813",
                "razon_social" => "Almacen Combustible Cobija",
                "informacion_contacto" => 73968390,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 77127167,
                "direccion" => "La Paz Av Arce",
                "NIT" => "6842092",
                "razon_social" => "Oficina Central",
                "informacion_contacto" => 77127167,
            ],

            [
                "nombres" => "GROVER",
                "apellido_paterno" => "ARAMAYO",
                "apellido_materno" => "RODRIGUEZ",
                "celular" => 68830208,
                "direccion" => "CALLE SANTA CRUZ N°247 ZONA \/ BARRIO  QUILLACOLLO",
                "NIT" => "7258497",
                "razon_social" => "GROVER ARAMAYO RODRIGUEZ",
                "informacion_contacto" => 4369030,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 78819186,
                "direccion" => "CALLE SANTA CRUZ N°466  ZONA ROSARIO",
                "NIT" => "7258497",
                "razon_social" => "SERGIO CESAR LAURA TOLA",
                "informacion_contacto" => 78819186,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 77546105,
                "direccion" => "CALLE VILUYO N° 1015  ESQ. ILLAMPU",
                "NIT" => "385358020",
                "razon_social" => "FERNANDO VILLAZANTE F",
                "informacion_contacto" => 77546105,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 67307187,
                "direccion" => "AVENIDA LAS AMERICAS N° 486 ZONA VILLA FATIMA",
                "NIT" => "10651827",
                "razon_social" => "ALISON NILCE GALLO RODAS",
                "informacion_contacto" => 67307187,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 77576829,
                "direccion" => "AV. RAMIRO CASTILLO N°20 ZONA KALAJAWIRA",
                "NIT" => "3306884011",
                "razon_social" => "PATRICIA ADELAIDA CHOQUE CUSIQUISPE",
                "informacion_contacto" => 77576829,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 2500188,
                "direccion" => "AV. PASTO GRANDE N°120 ZONA CHURIACA",
                "NIT" => "5790014019",
                "razon_social" => "EMPRESA GASOLCAMP SRL",
                "informacion_contacto" => 2500188,
            ],

            [
                "nombres" => "JUAN",
                "apellido_paterno" => "CORONADO",
                "apellido_materno" => "ZARATE",
                "celular" => 73476354,
                "direccion" => "Shinahota-Ibuelo",
                "NIT" => "3306884011",
                "razon_social" => "Planta Shinahota - Stevia",
                "informacion_contacto" => 73680438,
            ],

            [
                "nombres" => "CHRISTIAN",
                "apellido_paterno" => "VARGAS",
                "apellido_materno" => "SILVESTRE",
                "celular" => 72220302,
                "direccion" => "AV. RAFAEL URQUIDI N° 226",
                "NIT" => "3306884011",
                "razon_social" => "INDUSTRIAS QUIMICA NACIONAL",
                "informacion_contacto" => 4666555,
            ],

            [
                "nombres" => "JAIME AMERICO",
                "apellido_paterno" => "GOYONADA",
                "apellido_materno" => "CHAVARRIA",
                "celular" => 0,
                "direccion" => "CALLE COCHABAMBA, SORIA GALVARRO Y PLATA",
                "NIT" => "1024133029",
                "razon_social" => "GeneSys",
                "informacion_contacto" => 69579696,
            ],

            [
                "nombres" => "MARCO ANTONIO",
                "apellido_paterno" => "ALCONCE",
                "apellido_materno" => "SERRANO",
                "celular" => 0,
                "direccion" => "AV. BUSCH, BENEMERITOS",
                "NIT" => "6843158",
                "razon_social" => "DISTRIBUIDORA COMERCIAL ALCONCE",
                "informacion_contacto" => 70433185,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 0,
                "direccion" => "AV. PILCOMAYO NRO 222",
                "NIT" => "4152737",
                "razon_social" => "SPARTAN",
                "informacion_contacto" => 4124013,
            ],

            [
                "nombres" => "BARTHY FERNADO",
                "apellido_paterno" => "ALVAREZ",
                "apellido_materno" => "GRIFFITHS",
                "celular" => 0,
                "direccion" => "CALLE LANDEATA",
                "NIT" => "4121998",
                "razon_social" => "INSTRUMENTA",
                "informacion_contacto" => 2114568,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 61271494,
                "direccion" => "AV. 6 DE MARZO N°1001  ZONA VILLA BOLIVAR \"B\"",
                "NIT" => "1837031",
                "razon_social" => "CLAUDIA ASUNCION VALENCIA GUTIERREZ",
                "informacion_contacto" => 61271494,
            ],

            [
                "nombres" => "MARIBEL",
                "apellido_paterno" => "ESCOBAR",
                "apellido_materno" => "RODRIGUEZ",
                "celular" => 67417060,
                "direccion" => "CARRETERA VILLA TUNARI -ISINUTA",
                "NIT" => "7136612",
                "razon_social" => "CIP APICOLA SAMUZABETY",
                "informacion_contacto" => 68211917,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 77756434,
                "direccion" => "AV. ARCE",
                "NIT" => "10735497",
                "razon_social" => "DISTRIBUIDORA TARIJA",
                "informacion_contacto" => 221145,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 3849595,
                "direccion" => "AV. ARCE",
                "NIT" => "8510534017",
                "razon_social" => "DISTRIBUIDORA SAN AURELIO",
                "informacion_contacto" => 3489945,
            ],

            [
                "nombres" => "LUCIO",
                "apellido_paterno" => "VILLCA",
                "apellido_materno" => "CONDORI",
                "celular" => 8421290,
                "direccion" => "AV. 9 DE FEBRERO S\/N ZONA 11 DE OCTUBRE",
                "NIT" => "5048048",
                "razon_social" => "ESTACION DE SERVICIO LOS TAJIBOS",
                "informacion_contacto" => 8421290,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 3568899,
                "direccion" => "AV. ARCE",
                "NIT" => "7229784",
                "razon_social" => "DISTRIBUIDORA MONTERO",
                "informacion_contacto" => 3489945,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 67890665,
                "direccion" => "AV. ARCE",
                "NIT" => "10649699",
                "razon_social" => "DISTRIBUIDORA POTOSI",
                "informacion_contacto" => 3489945,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 77756434,
                "direccion" => "AV. ARCE",
                "NIT" => "10401014",
                "razon_social" => "DISTRIBUIDORA EQUIPETROL",
                "informacion_contacto" => 3489945,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 60625018,
                "direccion" => "ZONA \/BARIO : PACAJES",
                "NIT" => "5786649",
                "razon_social" => "VERYQUIMIC LTDA",
                "informacion_contacto" => 60625018,
            ],

            [
                "nombres" => "ALEXANDER",
                "apellido_paterno" => "OQUENDO",
                "apellido_materno" => "M",
                "celular" => 76201554,
                "direccion" => "AV. SALAMANCA N 917 EDIF. CIBELES PISO 6 ZONA CENTRAL",
                "NIT" => "5053239",
                "razon_social" => "SAMO S.A.",
                "informacion_contacto" => 4525100,
            ],

            [
                "nombres" => "ROBERTO",
                "apellido_paterno" => "ZEBALLOS",
                "apellido_materno" => "S.A",
                "celular" => 60397763,
                "direccion" => "AVENIDA MORTENSON  IVIRGARZAMA",
                "NIT" => "6843158",
                "razon_social" => "AUTOREPUESTOS\EL CHOCO",
                "informacion_contacto" => 60397763,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 4250105,
                "direccion" => "CALLE NATANIEL AGUIRRE N° 666",
                "NIT" => "1826291",
                "razon_social" => "LUSSAC LTDA.",
                "informacion_contacto" => 4250105,
            ],

            [
                "nombres" => "NOEL HAYDER",
                "apellido_paterno" => "MUÑOZ",
                "apellido_materno" => "LARA",
                "celular" => 69490216,
                "direccion" => "CALLE INNOMINADA  BARIO VILLA LA AGUADA",
                "NIT" => "7229784",
                "razon_social" => "FAFORAL",
                "informacion_contacto" => 4219403,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 4299110,
                "direccion" => "AVENIDA VILLAZON S\/N ZONA PACATA BAJA",
                "NIT" => "1862390",
                "razon_social" => "INPROCO S.R.L.",
                "informacion_contacto" => 4299110,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 68534563,
                "direccion" => "AVENIDA MORTENZON  NRO S\/N  ZONA\/BARRIO CENTRAL - IVIRGARZAMA",
                "NIT" => "7169270",
                "razon_social" => "DICKIE GIL AVILEZ",
                "informacion_contacto" => 68534563,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 72057784,
                "direccion" => "CALLE COMERCIO ESQ. YANACOCHA N° 979 ZONA CENTRAL",
                "NIT" => "385358020",
                "razon_social" => "MANUFACTURA BOLIVIANA S.A",
                "informacion_contacto" => 2406604,
            ],

            [
                "nombres" => "SANDRA ALEGRE",
                "apellido_paterno" => "ALEGRE",
                "apellido_materno" => "YAHURI",
                "celular" => 34567781,
                "direccion" => "AV. TRINIDAD",
                "NIT" => "4121014",
                "razon_social" => "DISTRIBUIDORA TRINIDAD",
                "informacion_contacto" => 2456678,
            ],

            [
                "nombres" => "IMPORTADORA DE IDEAS S.A.",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 2118914,
                "direccion" => "AV. ARCE PINILLA - CAMPOS S\/N",
                "NIT" => "7186054",
                "razon_social" => "IMPORTADORA DE IDEAS S.A.",
                "informacion_contacto" => 2118914,
            ],

            [
                "nombres" => "IMP. SANTA CLARA PINTO REY S.R.L.",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 1,
                "direccion" => "CALLE INCACHACA NRO 553",
                "NIT" => "1829367013",
                "razon_social" => "IMP. SANTA CLARA PINTO REY S.R.L.",
                "informacion_contacto" => 1,
            ],

            [
                "nombres" => "JULIA JUANA ZUÑAGUA APAZA",
                "apellido_paterno" => "JULIA JUANA",
                "apellido_materno" => "ZUÑAGUA",
                "celular" => 60603795,
                "direccion" => "AV. PERU NRO 207 ZONA NORTE",
                "NIT" => "5811836",
                "razon_social" => "CENTRO DE PLASTICOS",
                "informacion_contacto" => 2283210,
            ],

            [
                "nombres" => "XIMENA DARIA",
                "apellido_paterno" => "LEON",
                "apellido_materno" => "ASTURIZAGA",
                "celular" => 67009458,
                "direccion" => "AVENIDA POTOSI N°716 ZONA CENTRAL",
                "NIT" => "3980575",
                "razon_social" => "INOX SUPPLY INGENIERIA",
                "informacion_contacto" => 2287001,
            ],

            [
                "nombres" => "ESTHER MARIA RAMOS CONDORI",
                "apellido_paterno" => "ESTHER MARIA",
                "apellido_materno" => "RAMOS",
                "celular" => 70544461,
                "direccion" => "CALLE INCACHACA NRO 569",
                "NIT" => "5032110",
                "razon_social" => "ESTHER MARIA RAMOS CONDORI",
                "informacion_contacto" => 1,
            ],

            [
                "nombres" => "ZEYLA",
                "apellido_paterno" => "GARCIA",
                "apellido_materno" => "HUAYLLAS",
                "celular" => 72565586,
                "direccion" => "ZONA 14 DE SEPTIEMBRE",
                "NIT" => "7158728",
                "razon_social" => "COMERCIAL JAZEY",
                "informacion_contacto" => 2459753,
            ],

            [
                "nombres" => "MODESTA",
                "apellido_paterno" => "LUNA",
                "apellido_materno" => ".",
                "celular" => 71904494,
                "direccion" => "CALLE INCACHACA NRO 637",
                "NIT" => "7247501014",
                "razon_social" => "COMERCIAL\LUNA",
                "informacion_contacto" => 2450047,
            ],

            [
                "nombres" => "RIOZETH VICTORIA",
                "apellido_paterno" => "TAQUICHIRI",
                "apellido_materno" => "CHOQUELLATA",
                "celular" => 60739337,
                "direccion" => "AVENIDA OQUENDO NRO 888",
                "NIT" => "7110795",
                "razon_social" => "COMERCIAL GABRIEL ACCESORIOS DE GOMERIA",
                "informacion_contacto" => 4668224,
            ],

            [
                "nombres" => "DAYANA EDITH",
                "apellido_paterno" => "NINA",
                "apellido_materno" => "AYORA",
                "celular" => 67409888,
                "direccion" => "AV. CHUQUISACA",
                "NIT" => "5812324",
                "razon_social" => "FERRO - NINA AYOROA",
                "informacion_contacto" => 1,
            ],

            [
                "nombres" => "PAULINA",
                "apellido_paterno" => "ALTAMIRANO",
                "apellido_materno" => ".",
                "celular" => 71878799,
                "direccion" => "CALLE RODOLFO AVILA S\/N BARRIO SAN LORENZO",
                "NIT" => "1887366",
                "razon_social" => "INVAR",
                "informacion_contacto" => 6640110,
            ],

            [
                "nombres" => "SN",
                "apellido_paterno" => "SA",
                "apellido_materno" => "SA",
                "celular" => 0,
                "direccion" => "AV. BALLIVIAN PRADO N° 753 Z\/ B CENTRAL",
                "NIT" => "7103656",
                "razon_social" => "HIPERMAXI S.A.",
                "informacion_contacto" => 0,
            ],

            [
                "nombres" => "LE MANS LTDA",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 1,
                "direccion" => "AV. CRISTO REDENTOR, ESQ. CUARTO ANILLO",
                "NIT" => "7258497",
                "razon_social" => "LE MANS LTDA",
                "informacion_contacto" => 3412824,
            ],

            [
                "nombres" => "JUAN PABLO",
                "apellido_paterno" => "QUENTA",
                "apellido_materno" => "OROSCO",
                "celular" => 79603057,
                "direccion" => "CALLE AVAROA NRO 403, ZONA: OBISPO BOSQUE",
                "NIT" => "10654916",
                "razon_social" => "SERVICIOS DE IMPRECION PRYNK",
                "informacion_contacto" => 1,
            ],

            [
                "nombres" => "JULIO",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "VEIZAGA",
                "celular" => 79120354,
                "direccion" => "EDIFICIO MULTICENTRO SANTA CRUZ P.B. TIENDA 300",
                "NIT" => "7258497",
                "razon_social" => "GLAMAR",
                "informacion_contacto" => 2452871,
            ],

            [
                "nombres" => "HERMENEGILDA MABEL",
                "apellido_paterno" => "CADENA",
                "apellido_materno" => "SOSA",
                "celular" => 77770846,
                "direccion" => "CALLE MURILLO NRO 1191 ZONA CENTRAL",
                "NIT" => "1877756",
                "razon_social" => "TRIPLE @ PUBLICIDAD",
                "informacion_contacto" => 2317893,
            ],

            [
                "nombres" => "HANNA",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 70284684,
                "direccion" => "LA PAZ - BOLIVIA",
                "NIT" => "5798071",
                "razon_social" => "HANNA INSTRUMENTS EQUIPOS BOLIVIA S.R.L.",
                "informacion_contacto" => 3120130,
            ],

            [
                "nombres" => "TOYASA S.A.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 78513163,
                "direccion" => "AVENIDA CRISTO REDENTOR NRO 777",
                "NIT" => "4137983",
                "razon_social" => "TOYOSA S.A.",
                "informacion_contacto" => 3425227,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 0,
                "direccion" => "CALLE DIAZ ROMERO, EDIFICIO URQUIZO, MEZZANINE OF.1 N° 1545 ZONA MIRA FLORES",
                "NIT" => "7247417",
                "razon_social" => "IMPLELAB S.R.L.",
                "informacion_contacto" => 2243271,
            ],

            [
                "nombres" => "DAYSON",
                "apellido_paterno" => "LIMA",
                "apellido_materno" => "BALBOA",
                "celular" => 68464502,
                "direccion" => "ZONA\/BARRIO LOS TUSEQUIS UV. 075 MZ: 023",
                "NIT" => "5022095",
                "razon_social" => "MEDIANA",
                "informacion_contacto" => 76010711,
            ],

            [
                "nombres" => "DECORACIONES BRASILIA S.R.L.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 2796464,
                "direccion" => "AVENIDA BALLIVIAN NRO7971",
                "NIT" => "6836298",
                "razon_social" => "DECORACIONES BRASILIA S.R.L.",
                "informacion_contacto" => 2796464,
            ],

            [
                "nombres" => "MULTICENTER S.R.L.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 3431700,
                "direccion" => "4TO ANILLO B\/COSTANERA",
                "NIT" => "5042296",
                "razon_social" => "MULTICENTER S.R.L.",
                "informacion_contacto" => 3431700,
            ],

            [
                "nombres" => "CLAUDIA DANIELA",
                "apellido_paterno" => "ROJAS",
                "apellido_materno" => "ALMARAZ",
                "celular" => 71028073,
                "direccion" => "AVENIDA RADIAL 19 NRO S\/N",
                "NIT" => "7194431",
                "razon_social" => "ASERCOM",
                "informacion_contacto" => 3597597,
            ],

            [
                "nombres" => "HIPERMAXI S.A.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 3115575,
                "direccion" => "AVENIDA ROCA Y CORONADO NRO 800",
                "NIT" => "5054030",
                "razon_social" => "HIPERMAXI S.A.",
                "informacion_contacto" => 3115575,
            ],

            [
                "nombres" => "GROVER",
                "apellido_paterno" => "ESPEJO",
                "apellido_materno" => "QUISPE",
                "celular" => 71544638,
                "direccion" => "EL ALTO ZONA VILLA BOLIVAR YKK CALLE 3 NRO. 100",
                "NIT" => "7201873",
                "razon_social" => "PLANTA DE DERIVADOS EL ALTO",
                "informacion_contacto" => 22826568,
            ],

            [
                "nombres" => "JIMMY WILSON",
                "apellido_paterno" => "ORELLANA",
                "apellido_materno" => "CALVI",
                "celular" => 0,
                "direccion" => "AV. 6 DE AGOSTO NRO 1216 ZONA JAIHUAYCO",
                "NIT" => "2762360",
                "razon_social" => "INETYF",
                "informacion_contacto" => 76948096,
            ],

            [
                "nombres" => "MARTHA",
                "apellido_paterno" => "ZEBALLOS",
                "apellido_materno" => "COSSIO",
                "celular" => 2444015,
                "direccion" => "AV. INOFUENTES  N° 1762 EDF. MARIA BELEN",
                "NIT" => "5042371",
                "razon_social" => "LABOCENTRO",
                "informacion_contacto" => 2444015,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 68694451,
                "direccion" => "calle s\/n carretera Panamericana km 4 al lado del matadero",
                "NIT" => "5042371",
                "razon_social" => "INDUSTRIA COMERCIAL EL PORTILLO S.R.L",
                "informacion_contacto" => 46676645,
            ],

            [
                "nombres" => "MARIA SEBASTIANA",
                "apellido_paterno" => "CARDOZO",
                "apellido_materno" => "QUIROGA",
                "celular" => 46661077,
                "direccion" => "CALLE SAN JUAN S\/N BARRIO LA LOMA",
                "NIT" => "5042371",
                "razon_social" => "FERRETERIA MARYS",
                "informacion_contacto" => 6661077,
            ],

            [
                "nombres" => "SANDRA",
                "apellido_paterno" => "CLAURE",
                "apellido_materno" => "DIAZ",
                "celular" => 67546170,
                "direccion" => "CALLE MORTENSON N S\/N IVIRGARZAMA",
                "NIT" => "1877756",
                "razon_social" => "ELECTRO - MEC",
                "informacion_contacto" => 67546170,
            ],

            [
                "nombres" => "RAQUEL ALISON",
                "apellido_paterno" => "OCHOA",
                "apellido_materno" => "PATZI",
                "celular" => 73226070,
                "direccion" => "CALLE ELOY SALMON#859, EDIFICIO SAN SILVESTRE PISO 2 ZONA GRAN PODER",
                "NIT" => "5032110",
                "razon_social" => "OFFICE SHOP",
                "informacion_contacto" => 73226070,
            ],

            [
                "nombres" => "JINGLER",
                "apellido_paterno" => "PEREDO",
                "apellido_materno" => "PASCUAL",
                "celular" => 70381125,
                "direccion" => "AV. MORTENSON N° S\/N IVIRGARZAMA",
                "NIT" => "12351741",
                "razon_social" => "FERRETERIA PEREDO",
                "informacion_contacto" => 70381125,
            ],

            [
                "nombres" => "CRISTINA MARIELA",
                "apellido_paterno" => "TEJERINA",
                "apellido_materno" => ".",
                "celular" => 6638423,
                "direccion" => "AV. PANAMERICANA S\/N BARRIO LOS ALAMOS",
                "NIT" => "1877756",
                "razon_social" => "COMERCIAL LUPE",
                "informacion_contacto" => 6638423,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 75200521,
                "direccion" => "Av. Lte. Oquendo # 249",
                "NIT" => "1833316",
                "razon_social" => "ELIOINDUSTRIAL&COMERCIALIZACION",
                "informacion_contacto" => 2281113,
            ],

            [
                "nombres" => "NELSON JOHNY",
                "apellido_paterno" => "ALBA",
                "apellido_materno" => "MEDRANO",
                "celular" => 4610204,
                "direccion" => "SHINANOTA",
                "NIT" => "7500807",
                "razon_social" => "NELSON JOHNY ALBA MEDRANO",
                "informacion_contacto" => 4610204,
            ],

            [
                "nombres" => "ELSA",
                "apellido_paterno" => "BELLIDO",
                "apellido_materno" => ".",
                "celular" => 6292578,
                "direccion" => "CALLE AYACUCHO S\/N - CAMARGO - CHUQUISACA - BOLIVIA",
                "NIT" => "1359744",
                "razon_social" => "Distribuidora de G.L.P. CAMARGO",
                "informacion_contacto" => 6292578,
            ],

            [
                "nombres" => "NELSON",
                "apellido_paterno" => "CHOQUEVILLCA",
                "apellido_materno" => "MAMANI",
                "celular" => 0,
                "direccion" => "AV.  MARCELO QUIROGA SANTA CRUZ",
                "NIT" => "6136540",
                "razon_social" => "AUTO PARTES\TOÑO DIESEL",
                "informacion_contacto" => 6467544,
            ],

            [
                "nombres" => "ALFREDO",
                "apellido_paterno" => "INTURIAS",
                "apellido_materno" => "PITA",
                "celular" => 74052641,
                "direccion" => "Calle Juana Azurduy de Padilla - Villa 14 de Septiembre",
                "NIT" => "8568041",
                "razon_social" => "FERRETERIA\AVC - INTURIAS",
                "informacion_contacto" => 74052641,
            ],

            [
                "nombres" => "ADHEMAR",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "CHOQUE",
                "celular" => 78366193,
                "direccion" => "PASAJE 1 Y CALLE DALENCE",
                "NIT" => "7247501014",
                "razon_social" => "FOX-BOLIVIA",
                "informacion_contacto" => 78366193,
            ],

            [
                "nombres" => "JUAN CARLOS",
                "apellido_paterno" => "PEREZ",
                "apellido_materno" => "VILLALBA",
                "celular" => 75584437,
                "direccion" => "AV. PORVENIR N° 272 MONTEAGUDO - CHUQUISACA",
                "NIT" => "1852076",
                "razon_social" => "ELECTROLUZ INDUSTRIAL",
                "informacion_contacto" => 75584437,
            ],

            [
                "nombres" => "EDITORIAL HERMENCA LTD.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 2441406,
                "direccion" => "CALLE FEDERICO ZUAZO N° 1913",
                "NIT" => "5055014",
                "razon_social" => "EDITORIAL HERMENCA LTDA.\DIGITAL",
                "informacion_contacto" => 2441406,
            ],

            [
                "nombres" => "GLORIA",
                "apellido_paterno" => "RODRIQUEZ",
                "apellido_materno" => "RAMOS",
                "celular" => 78695689,
                "direccion" => "CALLE LOS OLIVOS N° 5 MONTEAGUDO, CHUQUISACA_BOLIVIA",
                "NIT" => "7017893",
                "razon_social" => "TALLER MECANICA INTEGRAL\EL CHAQUEÑO",
                "informacion_contacto" => 78695689,
            ],

            [
                "nombres" => "SUPERMERCADO ONLIS S.R.L.",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 78906543,
                "direccion" => "CALLE AHITI EDIFICIO TROCHE PISO PB LOCAL 1 NRO. 1318",
                "NIT" => "1887970",
                "razon_social" => "SUPERMERCADO ONLIS S.R.L.",
                "informacion_contacto" => 6788945,
            ],

            [
                "nombres" => "ROCIÓ ANGELA",
                "apellido_paterno" => "QUINTANILLA",
                "apellido_materno" => "FAJARRI",
                "celular" => 73708236,
                "direccion" => "AV. DE LAS AMERICAS N° 465 EDIF. S\/N PISO PB EXTERNA DEPTO. LOCAL 11",
                "NIT" => "7198008",
                "razon_social" => "FERRETERIA YAMILE",
                "informacion_contacto" => 23456787,
            ],

            [
                "nombres" => "MARIA ANGELICA",
                "apellido_paterno" => "QUISPE",
                "apellido_materno" => "ROJAS",
                "celular" => 70647479,
                "direccion" => "PASAJE VIRGEN DEL ROSARIO N° ND-05 ZONA EL ROSARIO",
                "NIT" => "6042020",
                "razon_social" => "DISTRIBUIDORA YESICA CARLA YC",
                "informacion_contacto" => 2462878,
            ],

            [
                "nombres" => "SEBASTIAN",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "SELAEZ",
                "celular" => 70552931,
                "direccion" => "AV. MONTES N° 692, ZONA SAN SEBASTIAN",
                "NIT" => "5008321",
                "razon_social" => "GS IMPORTADORA & EXPORTADORA FLORES",
                "informacion_contacto" => 2004297,
            ],

            [
                "nombres" => "MOISÉS ADOLFO",
                "apellido_paterno" => "ARANDA",
                "apellido_materno" => "ROCHA",
                "celular" => 77743709,
                "direccion" => "CALLE MURILLO N° 1046, ZONA: BELEN",
                "NIT" => "7225292",
                "razon_social" => "BAZAR FERRETERÍA\MARCEL",
                "informacion_contacto" => 2315557,
            ],

            [
                "nombres" => "CALIXTO",
                "apellido_paterno" => "LLIULLI",
                "apellido_materno" => "YUJRA",
                "celular" => 73537388,
                "direccion" => "CALLE 16 N° 4 EDIFICIO SIN NOMBRE PISO: PB DEPTO. ZONA ACHUMANI",
                "NIT" => "4120185",
                "razon_social" => "LIBRERÍA GRAFITO",
                "informacion_contacto" => 2587920,
            ],

            [
                "nombres" => "RICHARD MOISES",
                "apellido_paterno" => "VENGAS",
                "apellido_materno" => "QUISPE",
                "celular" => 4489160,
                "direccion" => "AV. REPUBLICA CASI ESQ. 16 DE JULIO N° 777",
                "NIT" => "7247501014",
                "razon_social" => "COMERCIAL \VENEGAS",
                "informacion_contacto" => 4489160,
            ],

            [
                "nombres" => "HENRY JHAROLD",
                "apellido_paterno" => "QUISPE",
                "apellido_materno" => "VILLCA",
                "celular" => 73561898,
                "direccion" => "AV. TEJADA SORZANO N° 317",
                "NIT" => "7136612",
                "razon_social" => "FERRETERIA\RUTH - BEL",
                "informacion_contacto" => 57879900009,
            ],

            [
                "nombres" => "SARA APOLINIA",
                "apellido_paterno" => "YAVE",
                "apellido_materno" => "CONDORI",
                "celular" => 7352985,
                "direccion" => "EDIF. CANADA PISO PB DEPTO. LOCAL 1",
                "NIT" => "1389824",
                "razon_social" => "LIBRERÍA\ZARA",
                "informacion_contacto" => 2375357,
            ],

            [
                "nombres" => "KETAL S.A.  SUCURSAL",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 78328344,
                "direccion" => "AV. REPÚBLICA ESTACIÓN TELEFÉRICO NARANJA PB",
                "NIT" => "5050958016",
                "razon_social" => "KETAL S.A. \SUCURSAL N° 27",
                "informacion_contacto" => 2791122,
            ],

            [
                "nombres" => "PASTOR ROLANDO",
                "apellido_paterno" => "ROCA",
                "apellido_materno" => "LUNA",
                "celular" => 0,
                "direccion" => "CALLE MURILLO NRO. 960 ZONA CENTRAL LA PAZ",
                "NIT" => "1843675",
                "razon_social" => "METALGRAFT",
                "informacion_contacto" => 2337478,
            ],

            [
                "nombres" => "RAQUEL",
                "apellido_paterno" => "QUENTA",
                "apellido_materno" => "HILARI",
                "celular" => 73232901,
                "direccion" => "AV. JORGE CARASCO NRO. 100 ZONA 12 DE OCTUBRE LA PAZ",
                "NIT" => "2786160",
                "razon_social" => "IMPORTADORA RAQZELDY",
                "informacion_contacto" => 2823678,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 0,
                "direccion" => "CALLE HILBO NRO. 700 ZONA BARRIO PUCARANI EL ALTO",
                "NIT" => "6152790",
                "razon_social" => "TRATERMO S.R.L.",
                "informacion_contacto" => 2852767,
            ],

            [
                "nombres" => "MELY MELANIA",
                "apellido_paterno" => "CANCHI",
                "apellido_materno" => "MAMANI",
                "celular" => 74534072,
                "direccion" => "AV. MEJILLONES N° 608 BARRIO AVAROA",
                "NIT" => "7109346",
                "razon_social" => "COMERCIAL MELANY",
                "informacion_contacto" => 76199954,
            ],

            [
                "nombres" => "VICENTE",
                "apellido_paterno" => "SUYO",
                "apellido_materno" => "MARCA",
                "celular" => 72783080,
                "direccion" => "AV. 9 DE ABRIL NRO. 1860",
                "NIT" => "6152790",
                "razon_social" => "MECÁNICA AUTOMOTRIZ\NEFIMOTORS",
                "informacion_contacto" => 4549239,
            ],

            [
                "nombres" => "DAYSON",
                "apellido_paterno" => "LIMA",
                "apellido_materno" => "BALBOA",
                "celular" => 68464502,
                "direccion" => "CARANAVI-LA PAZ-BOLIVIA",
                "NIT" => "10659843",
                "razon_social" => "ESTACION DE SERVICIOS YARA S.R.L.",
                "informacion_contacto" => 2234868,
            ],

            [
                "nombres" => "PRU ROBIN SRL",
                "apellido_paterno" => "A",
                "apellido_materno" => "A",
                "celular" => 4576989,
                "direccion" => "PLAZA FRANZ TAMAYO N°1923",
                "NIT" => "5032110",
                "razon_social" => "PRU-ROBIN SRL",
                "informacion_contacto" => 2442202,
            ],

            [
                "nombres" => "VICTOR HUGO",
                "apellido_paterno" => "SAINZ",
                "apellido_materno" => "ILLANES",
                "celular" => 76569901,
                "direccion" => "CALLE BALTAZAR ALQUIZA N° 702",
                "NIT" => "3045711",
                "razon_social" => "VISA",
                "informacion_contacto" => 35658789,
            ],

            [
                "nombres" => "VENANCIO",
                "apellido_paterno" => "NINA",
                "apellido_materno" => "MAMANI",
                "celular" => 0,
                "direccion" => "AV.DE LA RESISTENCIA ZONA ETERAZAMA",
                "NIT" => "5032110",
                "razon_social" => "FERRETERIA \"ETERAZAMA\"",
                "informacion_contacto" => 71737036,
            ],

            [
                "nombres" => "JULIO CESAR",
                "apellido_paterno" => "COVARRUBIAS",
                "apellido_materno" => "AREVALO",
                "celular" => 0,
                "direccion" => "CALLE PADILLA ESQ.AV.BARRIENTOS BARRIO LAICACOTA",
                "NIT" => "5032110",
                "razon_social" => "COMERCIAL BARRIENTOS",
                "informacion_contacto" => 4705057,
            ],

            [
                "nombres" => "SERGIO ANTONIO",
                "apellido_paterno" => "URIA",
                "apellido_materno" => "GUTIERREZ",
                "celular" => 0,
                "direccion" => "AV.BLANCO GALLIDO N°ZONA BARRIO COÑA COÑA",
                "NIT" => "2200847",
                "razon_social" => "EMPRESA TODO ELÉCTRICO",
                "informacion_contacto" => 4362023,
            ],

            [
                "nombres" => "MARIA ISABEL",
                "apellido_paterno" => "LAURA",
                "apellido_materno" => "SILVA",
                "celular" => 77511048,
                "direccion" => "AV. 6 DE MARZO NRO. 145 ZONA 12 DE OCTUBRE",
                "NIT" => "6141177",
                "razon_social" => "DISTRIBUIDORA \"J&M\"",
                "informacion_contacto" => 67056306,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 0,
                "direccion" => "CALLE BALLIVIAN Nro. 1456 Edificio Cervantes Mzne 2",
                "NIT" => "850450",
                "razon_social" => "TECNICA DE FLUIDOS BOLIVIA SRL",
                "informacion_contacto" => 2145194,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 71908989,
                "direccion" => "CALLE LANDAETA N° 262 EDIF. FRANZ TAMAYO",
                "NIT" => "5032110",
                "razon_social" => "BARTHY FERNANDO ALVAREZ GRIFFITHS",
                "informacion_contacto" => 71908989,
            ],

            [
                "nombres" => "ERLAN PEDRO",
                "apellido_paterno" => "LEIVA",
                "apellido_materno" => "BALTAZAR",
                "celular" => 69394917,
                "direccion" => "AV. PEDRO IGNACIO MUIBA N°130",
                "NIT" => "5032110",
                "razon_social" => "FERRO COMERCIAL\LOS TAJIBALES",
                "informacion_contacto" => 4623137,
            ],

            [
                "nombres" => "NEYSA",
                "apellido_paterno" => "CHAMBILLA",
                "apellido_materno" => "HUANACO",
                "celular" => 71122679,
                "direccion" => "AV. PEDRO IGNACIO MUIBA",
                "NIT" => "5813408",
                "razon_social" => "FERROTRUPER",
                "informacion_contacto" => 4631547,
            ],

            [
                "nombres" => "EVELIN ROMANE",
                "apellido_paterno" => "AYALA",
                "apellido_materno" => "GARCIA",
                "celular" => 71145470,
                "direccion" => "CALLE LAZARO DE RIBERA N° 134",
                "NIT" => "7181391",
                "razon_social" => "FERRETERIA FERNANDITA",
                "informacion_contacto" => 34634921,
            ],

            [
                "nombres" => "VELOMAN INDUSTRIAL S.R.L",
                "apellido_paterno" => "VELOMAN INDUSTRIAL S.R.L",
                "apellido_materno" => "VELOMAN INDUSTRIAL S.R.L",
                "celular" => 71522637,
                "direccion" => "AV. MONTES N° 456",
                "NIT" => "7258497",
                "razon_social" => "VELOMAN INDUSTRIAL S.R.L",
                "informacion_contacto" => 2463670,
            ],

            [
                "nombres" => "ELECTRORED BOLIVIA S.R.L",
                "apellido_paterno" => "ELECTRORED BOLIVIA S.R.L",
                "apellido_materno" => "ELECTRORED BOLIVIA S.R.L",
                "celular" => 2282429,
                "direccion" => "AV. MONTES N° 605",
                "NIT" => "3190506",
                "razon_social" => "ELECTRORED BOLIVIA S.R.L",
                "informacion_contacto" => 2282429,
            ],

            [
                "nombres" => "SN",
                "apellido_paterno" => "SN",
                "apellido_materno" => "SN",
                "celular" => 68490589,
                "direccion" => "CALLE JOSE CHAVEZ N° S\/N, ZONA\/BARRIO: CENTRAL",
                "NIT" => "5013311",
                "razon_social" => "MULTINEGOCIOS DEL TROPICO  S.R.L.",
                "informacion_contacto" => 68490589,
            ],

            [
                "nombres" => "TATIANA",
                "apellido_paterno" => "ESPINOZA",
                "apellido_materno" => "TORREZ",
                "celular" => 0,
                "direccion" => "VILLA TUNARI",
                "NIT" => "5792428",
                "razon_social" => "TATIANA ESPINOZA TORREZ",
                "informacion_contacto" => 0,
            ],

            [
                "nombres" => "..",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 0,
                "direccion" => "CALLE BENJAMIN BLANCO N°852",
                "NIT" => "7224731",
                "razon_social" => "CHRIS",
                "informacion_contacto" => 75989693,
            ],

            [
                "nombres" => "DELIA",
                "apellido_paterno" => "SANGUEZA",
                "apellido_materno" => "ANTEZANA",
                "celular" => 0,
                "direccion" => "CALLE AYACUCHO  ENTRE WASHINGTON",
                "NIT" => "1327687",
                "razon_social" => "DELIA SANGUEZA ANTEZANA",
                "informacion_contacto" => 5252455,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 71426747,
                "direccion" => "C. GROVER SUAREZ NRO 198",
                "NIT" => "5042371",
                "razon_social" => "IMACLARABELLA S.R.L.",
                "informacion_contacto" => 4068018,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 76233188,
                "direccion" => "Av. Mutualista Nº 100, 8vo anillo, Ciudad Santa Cruz",
                "NIT" => "7258497",
                "razon_social" => "SERVIRACK SRL",
                "informacion_contacto" => 3426272,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 0,
                "direccion" => "Parque Industrial P.I. Casilla Postal  Nº 704, Ciudad Santa Cruz",
                "NIT" => "4143803",
                "razon_social" => "MADEPA S.A.",
                "informacion_contacto" => 3491000,
            ],

            [
                "nombres" => "CLARIBEL",
                "apellido_paterno" => "CUELLAR",
                "apellido_materno" => "JIMENEZ",
                "celular" => 71681501,
                "direccion" => "CALLE SANTA BARBARA NRO 170 ZONA BARRIO CASCO VIEJO - SANTA CRUZ",
                "NIT" => "5050547",
                "razon_social" => "TECNOPACK M2I",
                "informacion_contacto" => 33324477,
            ],

            [
                "nombres" => "ROCIO",
                "apellido_paterno" => "ALIAGA",
                "apellido_materno" => "ALBERTO",
                "celular" => 69405547,
                "direccion" => "BARRIO SAN JOSE",
                "NIT" => "5812525",
                "razon_social" => "FERRETERIA COMERCIAL VICTORIA",
                "informacion_contacto" => 69405547,
            ],

            [
                "nombres" => "JUAN JOSE",
                "apellido_paterno" => "BAUTISTA",
                "apellido_materno" => "GUTIERREZ",
                "celular" => 8423251,
                "direccion" => "AV. 9 DE FEBRERO ESQ 27 DE MAYO",
                "NIT" => "4148554",
                "razon_social" => "ESTACION DE SERVICIO TISTY",
                "informacion_contacto" => 8423251,
            ],

            [
                "nombres" => "VELLARINA  YAZMIN",
                "apellido_paterno" => "JAVIER",
                "apellido_materno" => "ALVAREZ",
                "celular" => 76528260,
                "direccion" => "AV. DE LAS AMÉRICAS N° 435",
                "NIT" => "7252823",
                "razon_social" => "FERRETERÍA ELECTROCONS",
                "informacion_contacto" => 2262811,
            ],

            [
                "nombres" => "FLORA FLORENTINA",
                "apellido_paterno" => "CANAZA",
                "apellido_materno" => "CHINO",
                "celular" => 76745419,
                "direccion" => "AV. DE LAS AMÉRICAS N° 325",
                "NIT" => "5042371",
                "razon_social" => "FERRETERÍA GRABIEL",
                "informacion_contacto" => 2345667,
            ],

            [
                "nombres" => "ALVARO",
                "apellido_paterno" => "QUISPE",
                "apellido_materno" => "TAPIA",
                "celular" => 78745902,
                "direccion" => "AV. BENI S\/N (ZONA FATIMA)",
                "NIT" => "1872164",
                "razon_social" => "MOTOREPUESTOS \ULTRAMOTO",
                "informacion_contacto" => 78745902,
            ],

            [
                "nombres" => "JOSE ERNESTO",
                "apellido_paterno" => "ZEBALLOS",
                "apellido_materno" => "SANCHEZ",
                "celular" => 67359318,
                "direccion" => "AV. PANAMERICANA FRENTE SURT. IRIARTE",
                "NIT" => "10699585",
                "razon_social" => "LUBRICANTES \NUEVA TRINIDAD",
                "informacion_contacto" => 4635262,
            ],

            [
                "nombres" => "LUISA MARGARITA",
                "apellido_paterno" => "AREBALOS",
                "apellido_materno" => "JAIMES",
                "celular" => 72819015,
                "direccion" => "AV. PANAMERICANA N° 34 ENTRE 3RA Y 4TA ENT. URB. C BARACE",
                "NIT" => "3306884011",
                "razon_social" => "COMERCIAL\JAIMES",
                "informacion_contacto" => 72819015,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 3453579,
                "direccion" => "Av. Alemana - Calle Tamarindo",
                "NIT" => "1877756",
                "razon_social" => "COIMSA S.R.L.",
                "informacion_contacto" => 3453579,
            ],

            [
                "nombres" => "RONALD",
                "apellido_paterno" => "CONDORI",
                "apellido_materno" => "ALI",
                "celular" => 761009942,
                "direccion" => "AV. 09 FEBRERO S\/N BARRIO 11 DE OCTUBRE",
                "NIT" => "1877756",
                "razon_social" => "COMERCIAL\ALI",
                "informacion_contacto" => 75109053,
            ],

            [
                "nombres" => "TEOFILO",
                "apellido_paterno" => "CALSINA",
                "apellido_materno" => "NINA",
                "celular" => 72751056,
                "direccion" => "Avenida República Nro 1021 Zona\/Barrio San Miguel",
                "NIT" => "4465683014",
                "razon_social" => "PROVEEDORA \"CALSINAS\"",
                "informacion_contacto" => 4029920,
            ],

            [
                "nombres" => "RUBEN",
                "apellido_paterno" => "LEIVA",
                "apellido_materno" => "ROSAS",
                "celular" => 72838423,
                "direccion" => "AV. PEDRO IGNACIO MUIBA ESQ. IBARE S\/N (ZONA POMPEYA)",
                "NIT" => "3306884011",
                "razon_social" => "FERRO COMERCIAL  \"ALCORNOQUE\"",
                "informacion_contacto" => 72839948,
            ],

            [
                "nombres" => "EDGAR RAMIRO",
                "apellido_paterno" => "AQUINO",
                "apellido_materno" => "LEDEZMA",
                "celular" => 71887724,
                "direccion" => "AV. DEL EJERCITO NACIONAL N° 908",
                "NIT" => "1435594",
                "razon_social" => "SERVITECA \"EDMAR\"",
                "informacion_contacto" => 5247417,
            ],

            [
                "nombres" => "ROXANA",
                "apellido_paterno" => "VERGARA",
                "apellido_materno" => "LOZA",
                "celular" => 73205162,
                "direccion" => "CALLE RICARDO BUSTAMANTE N° 1102",
                "NIT" => "3306884011",
                "razon_social" => "FAHAMA PRINT",
                "informacion_contacto" => 34567789,
            ],

            [
                "nombres" => "..",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 44724707,
                "direccion" => "Parque Demetrio Canelas",
                "NIT" => "10528096",
                "razon_social" => "CAJA DE SALUD DE CAMINOS  Y R.A.",
                "informacion_contacto" => 44724707,
            ],

            [
                "nombres" => "EDUARDO",
                "apellido_paterno" => "DELGADO",
                "apellido_materno" => ".",
                "celular" => 2431598,
                "direccion" => "AV. SANCHEZ LIMA  2696",
                "NIT" => "7230357",
                "razon_social" => "BERNARDO LABORATORIOS S.R.L.",
                "informacion_contacto" => 2431410,
            ],

            [
                "nombres" => "MANACO",
                "apellido_paterno" => "MANACO",
                "apellido_materno" => "MANACO",
                "celular" => 44262900,
                "direccion" => "Carretera a Oruro Km 14 1\/2, Cochabamba",
                "NIT" => "6585077",
                "razon_social" => "MANUFACTURA BOLIVIANA S.A.",
                "informacion_contacto" => 44262900,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 0,
                "direccion" => "CALLE 25 DE MAYO N ° 580",
                "NIT" => "5032110",
                "razon_social" => "DISTRIBUIDORA SAN RAFAEL LTDA.",
                "informacion_contacto" => 4223231,
            ],

            [
                "nombres" => "JUANA LUZMILLA",
                "apellido_paterno" => "ANGULO",
                "apellido_materno" => "ACOSTA",
                "celular" => 0,
                "direccion" => "AV. JUANA AZURDUY  N° 045",
                "NIT" => "7258497",
                "razon_social" => "ELECTROFRIO",
                "informacion_contacto" => 4258205,
            ],

            [
                "nombres" => "DAYSON",
                "apellido_paterno" => "LIMA",
                "apellido_materno" => "BALBOA",
                "celular" => 68464502,
                "direccion" => "CARANAVI-LA PAZ-BOLIVIA",
                "NIT" => "3306884011",
                "razon_social" => "DISTRIBUIDORA DE GAS \FLOR DEL NORTE S.R.L.",
                "informacion_contacto" => 800106006,
            ],

            [
                "nombres" => "LUIS ANGEL",
                "apellido_paterno" => "GUTIERREZ",
                "apellido_materno" => "IBAÑEZ",
                "celular" => 74086127,
                "direccion" => "SAGARNAGA NRO 557 ZONA\/BARRIO GRAN P.",
                "NIT" => "10706398",
                "razon_social" => "O.E.SRL",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "DAYSON",
                "apellido_paterno" => "LIMA",
                "apellido_materno" => "BALBOA",
                "celular" => 68464502,
                "direccion" => "La Paz - Bolivia",
                "NIT" => "7113350",
                "razon_social" => "EBAC INDUSTRIAL S.R.L.",
                "informacion_contacto" => 2311863,
            ],

            [
                "nombres" => "VERONICA",
                "apellido_paterno" => "SEVILLA PRADA",
                "apellido_materno" => "TEJERINA",
                "celular" => 6653575,
                "direccion" => "AV. LA PAZ N° 310 BARRIO VILLA FATIMA",
                "NIT" => "5422689",
                "razon_social" => "PLASTICOS EL CHANGUITO",
                "informacion_contacto" => 6661640,
            ],

            [
                "nombres" => "ELIZABETH",
                "apellido_paterno" => "YAÑEZ",
                "apellido_materno" => ".",
                "celular" => 6638966,
                "direccion" => "AV. INTEGRACION S\/N",
                "NIT" => "5052813",
                "razon_social" => "SUPERMERCADO URKUPIÑA",
                "informacion_contacto" => 6638966,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 6655777,
                "direccion" => "AV. LAS AMERICAS ESQ CAMPERO NRO S\/N",
                "NIT" => "3476523",
                "razon_social" => "FARMACIA CHAVEZ S.A.",
                "informacion_contacto" => 6655777,
            ],

            [
                "nombres" => "ROSAURA",
                "apellido_paterno" => "GONZALES",
                "apellido_materno" => "MUR",
                "celular" => 72948017,
                "direccion" => "CALLE CAMPERO N° 866 ZONA \/ BARRIO EL MOLINO",
                "NIT" => "7225562",
                "razon_social" => "LIBRERIA, PAPELERIA Y ESCRITORIO YIREH",
                "informacion_contacto" => 6666062,
            ],

            [
                "nombres" => "FREDDY",
                "apellido_paterno" => "FITA",
                "apellido_materno" => "TABOADA",
                "celular" => 73498846,
                "direccion" => "CALLE VENEZUELA N° 1025 BARRIO LA LOMA",
                "NIT" => "7101254",
                "razon_social" => "FREDDY FITA TABOADA",
                "informacion_contacto" => 6641809,
            ],

            [
                "nombres" => "DIONICIA",
                "apellido_paterno" => "VALENCIA",
                "apellido_materno" => "GUTIERREZ",
                "celular" => 74086127,
                "direccion" => "A.V JORGE CARRASCO N°1481 ZONA 12 DE OCTUBRE",
                "NIT" => "7237959",
                "razon_social" => "CASA DE PINTURAS",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "ARIEL DAVID",
                "apellido_paterno" => "ANGLES",
                "apellido_materno" => "RIVERA",
                "celular" => 74086127,
                "direccion" => "A.V JORGE CARRASCO N° 83 ZONA 12 DE OCTUBRE",
                "NIT" => "12623035",
                "razon_social" => "ARIEL DAVID ANGLES RIVERA",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "CRISTINA",
                "apellido_paterno" => "CRISPIN",
                "apellido_materno" => "CHAMBI",
                "celular" => 7353916,
                "direccion" => "AV. HÉROES DEL KM 7 N° 100 ZONA BOLÍVAR A",
                "NIT" => "7102196",
                "razon_social" => "LIBRERIA ABC",
                "informacion_contacto" => 73534916,
            ],

            [
                "nombres" => "OSCAR",
                "apellido_paterno" => "PARI",
                "apellido_materno" => "ESPEJO",
                "celular" => 65169697,
                "direccion" => "AV. JORGE CARRASCO N° 36 ENTRE CALLE 2 Y 3",
                "NIT" => "5799655010",
                "razon_social" => "OCEANO  DE COLORES",
                "informacion_contacto" => 2820410,
            ],

            [
                "nombres" => "GREGORIO",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "ARCANI",
                "celular" => 63220552,
                "direccion" => "ZONA SANTIAGO II N°  638",
                "NIT" => "7101054",
                "razon_social" => "MATERIAL DE CONSTRUCCIÓN",
                "informacion_contacto" => 63220552,
            ],

            [
                "nombres" => "FREDDY",
                "apellido_paterno" => "BALBOA",
                "apellido_materno" => "ACHA",
                "celular" => 73282361,
                "direccion" => "CALLE SAGARNAGA N°479",
                "NIT" => "4037944015",
                "razon_social" => "virgo",
                "informacion_contacto" => 73282361,
            ],

            [
                "nombres" => "BARBARA",
                "apellido_paterno" => "YUJRA",
                "apellido_materno" => "ESPINOZA",
                "celular" => 71245099,
                "direccion" => "CALLE JORGE CARRASCO  N°100 ZONA 12 DE OCTUBRE",
                "NIT" => "5784654",
                "razon_social" => "ALFOMBRAS LIMBERTH",
                "informacion_contacto" => 67024177,
            ],

            [
                "nombres" => "ANA CRISTINA",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "ACARAPI",
                "celular" => 74086127,
                "direccion" => "CALLE  2 N°70 ZONA 12 DE OCTUBRE",
                "NIT" => "7159256",
                "razon_social" => "LIBRERIA 6 DE MARZO",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "FANNY",
                "apellido_paterno" => "MARCA",
                "apellido_materno" => "VICENTE",
                "celular" => 74086127,
                "direccion" => "AV. JORGE CARRASCO N° 87  ZONA 12 DE OCTUBRE",
                "NIT" => "7116795",
                "razon_social" => "ARTÍCULOS DE FERRETERÍA Y MATERIAL DE CONSTRUCCIÓN VIRGO",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "REYNALDO",
                "apellido_paterno" => "TOLA",
                "apellido_materno" => "MAMANI",
                "celular" => 76786562,
                "direccion" => "AV. PANDO Nº 260 ZONA SAN SEBASTIAN",
                "NIT" => "7238676",
                "razon_social" => "VISION GRAFICA",
                "informacion_contacto" => 2463180,
            ],

            [
                "nombres" => "GLORIA",
                "apellido_paterno" => "RODRIGUEZ",
                "apellido_materno" => "RAMOS",
                "celular" => 75795686,
                "direccion" => "CALLE LOS OLIVOS ZONA SINAI MONTEAGUDO",
                "NIT" => "1313647010",
                "razon_social" => "TALLER MECANICO INTEGRAL \EL CHAQUEÑO",
                "informacion_contacto" => 78695689,
            ],

            [
                "nombres" => "TITO MULLER",
                "apellido_paterno" => "VARGAS",
                "apellido_materno" => "DELGADO",
                "celular" => 75911236,
                "direccion" => "CALLE BENJAMIN BLANCO N°826 ZONA LAS CUADRAS",
                "NIT" => "5033044014",
                "razon_social" => "TV TITOS CAR",
                "informacion_contacto" => 4554855,
            ],

            [
                "nombres" => "FRANCISCO",
                "apellido_paterno" => "MAMANI",
                "apellido_materno" => "..",
                "celular" => 0,
                "direccion" => "AV.PORVENIR ZONA SAN JOSE DEL BAÑDO",
                "NIT" => "7247501014",
                "razon_social" => "AUTREP \FRAMBEC",
                "informacion_contacto" => 6472679,
            ],

            [
                "nombres" => "VALENTIN",
                "apellido_paterno" => "TORO",
                "apellido_materno" => "SANDOVAL",
                "celular" => 0,
                "direccion" => "AV.PETROLERA ZONA PRIMERO DE MAYO",
                "NIT" => "3306884011",
                "razon_social" => "REPUESTOS  SAUCES",
                "informacion_contacto" => 6472285,
            ],

            [
                "nombres" => "PATRICIA MARIELA",
                "apellido_paterno" => "PAREDES",
                "apellido_materno" => "VARGAS",
                "celular" => 74086127,
                "direccion" => "CALLE 6 N° 97 ZONA 12 DE OCTUBRE",
                "NIT" => "5784558",
                "razon_social" => "PLASTIDEAS",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "JOSE LUIS",
                "apellido_paterno" => "SILVESTRE",
                "apellido_materno" => "VILA",
                "celular" => 69828340,
                "direccion" => "AV. LANDAETA N° 1055",
                "NIT" => "3791336",
                "razon_social" => "SILVESTRE BATTERY",
                "informacion_contacto" => 69828340,
            ],

            [
                "nombres" => "KAREN NOHELIA",
                "apellido_paterno" => "ZUÑAGUA",
                "apellido_materno" => "TICONA",
                "celular" => 74086127,
                "direccion" => "CALLE 3 N° 1211",
                "NIT" => "4146951",
                "razon_social" => "KAREN NOHELIA  ZUÑAGUA TICONA",
                "informacion_contacto" => 74086127,
            ],

            [
                "nombres" => "ESTHER MARILI",
                "apellido_paterno" => "CHIPANA",
                "apellido_materno" => "CANAZA",
                "celular" => 77218870,
                "direccion" => "AV. DE LAS AMÉRICAS N° 447 EDIF. S\/N PISO PB",
                "NIT" => "7141521",
                "razon_social" => "FERRETERIA \ESTHER",
                "informacion_contacto" => 77218870,
            ],

            [
                "nombres" => "YHOCIMAR",
                "apellido_paterno" => "FLORES",
                "apellido_materno" => "CONDORI",
                "celular" => 0,
                "direccion" => "AVENIDA DEL EJERCITO  ESQ. ANTOFAGASTA NRO 981",
                "NIT" => "7258497",
                "razon_social" => "COMERCIAL VIRGEN DE LAS PEÑAS",
                "informacion_contacto" => 0,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 0,
                "direccion" => "JUNIN N 477 LA PLATA Y PDTE MONTES",
                "NIT" => "7180828014",
                "razon_social" => "SUPERMERCADO GLOBAL S.R.L.",
                "informacion_contacto" => 5271824,
            ],

            [
                "nombres" => "MARIA AMANDA",
                "apellido_paterno" => "LICONA",
                "apellido_materno" => "DE GONZALES",
                "celular" => 67557010,
                "direccion" => "Calle Punata Nro. 609",
                "NIT" => "10640075",
                "razon_social" => "LIBRERIA \DOÑA AMANDA",
                "informacion_contacto" => 4258581,
            ],

            [
                "nombres" => "FLORIA LEONAR",
                "apellido_paterno" => "CONDORI",
                "apellido_materno" => "CHOQUE",
                "celular" => 73847173,
                "direccion" => "CALLE PAGADOR  ENTRE 1 DE NOVIEMBRE",
                "NIT" => "10667195",
                "razon_social" => "ACCESORIOS Y RODAMINETOS",
                "informacion_contacto" => 0,
            ],

            [
                "nombres" => "NESTOR RENE",
                "apellido_paterno" => "GONZALES",
                "apellido_materno" => "MARTINIC",
                "celular" => 71848074,
                "direccion" => "PAGADOR ENTRE HERRERA Y MONTECINOS NRO 5417 ZONA CENTRAL",
                "NIT" => "7258497",
                "razon_social" => "ROCOMIN",
                "informacion_contacto" => 5275863,
            ],

            [
                "nombres" => "..",
                "apellido_paterno" => "..",
                "apellido_materno" => "..",
                "celular" => 0,
                "direccion" => "CALLE 23 DE MARZO ZONA VILLA BUSCH NORTE",
                "NIT" => "5032110",
                "razon_social" => "TALLERES VILLAVICENCIO",
                "informacion_contacto" => 4429872,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 2484808,
                "direccion" => "CALLE HÉROES DEL ACRE N° 1577",
                "NIT" => "7162050",
                "razon_social" => "PERTEC S.R.L.",
                "informacion_contacto" => 2484808,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 2240070,
                "direccion" => "CALLE ARTURO POSNANKY N° 1184",
                "NIT" => "4857717",
                "razon_social" => "AMERICAN PRINTER S.R.L.",
                "informacion_contacto" => 2240070,
            ],

            [
                "nombres" => "DULCE MONICA",
                "apellido_paterno" => "VILLEGAS",
                "apellido_materno" => "CASTELLON",
                "celular" => 0,
                "direccion" => "6 DE OCTUBRE Y AYACUCHO U COCHABAMBA N° 5750",
                "NIT" => "7170376010",
                "razon_social" => "LIBRERIA Y PAPELERIA EL ESTUDIANTE",
                "informacion_contacto" => 5279372,
            ],

            [
                "nombres" => "ELIZABETH",
                "apellido_paterno" => "PIMENTEL",
                "apellido_materno" => "ZURITA",
                "celular" => 78703352,
                "direccion" => "AV. CIRCUNVALACION N° S\/N BARRIO 3 DE MAYO",
                "NIT" => "1011619025",
                "razon_social" => "LUBRICENTRO ZONA OIL",
                "informacion_contacto" => 67399903,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 4021580,
                "direccion" => "CALLE LOS GOMEROS. ZONA\/BARRIO SIRARI",
                "NIT" => "10686028",
                "razon_social" => "TETRA PAK S.R.L.",
                "informacion_contacto" => 4021580,
            ],

            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 72020303,
                "direccion" => "AV. ARCE N° 2896",
                "NIT" => "1859998",
                "razon_social" => "SMS INTEGRACIÓN Y CONTROL LTDA.",
                "informacion_contacto" => 2000002,
            ],

            [
                "nombres" => "SANDRA GRACIELA",
                "apellido_paterno" => "LEMA",
                "apellido_materno" => "MENDOZA",
                "celular" => 70798619,
                "direccion" => "Calle Uruguay",
                "NIT" => "178928029",
                "razon_social" => "FERRETERIA\/RODRY",
                "informacion_contacto" => 4252553,
            ],

            [
                "nombres" => "FRANCISCO",
                "apellido_paterno" => "CHUMACERO",
                "apellido_materno" => "MACHACA",
                "celular" => 77449758,
                "direccion" => "AVENIDA MORTENSON N° S/N",
                "NIT" => "1800714",
                "razon_social" => "CHUMACERO DIFERENTE",
                "informacion_contacto" => 77449758,
            ],

            [
                "nombres" => "JOSE LUIS",
                "apellido_paterno" => "ROCABADO",
                "apellido_materno" => "ALANES",
                "celular" => 71451381,
                "direccion" => "Av. Heroinas",
                "NIT" => "5074704",
                "razon_social" => "OMEGA CONTROL",
                "informacion_contacto" => 4580261,
            ],

            [
                "nombres" => "LUCY",
                "apellido_paterno" => "MERUVIA",
                "apellido_materno" => ".",
                "celular" => 77926929,
                "direccion" => "Calle 25 de Mayo",
                "NIT" => "2764913",
                "razon_social" => "SISTEM ELECTRIC EVOLUTION",
                "informacion_contacto" => 4511070,
            ],

            [
                "nombres" => "JOSE RONAL",
                "apellido_paterno" => "AGUILAR",
                "apellido_materno" => "LOPEZ",
                "celular" => 72260884,
                "direccion" => "AVENIDA MORTENZON N° S/N",
                "NIT" => "8959582",
                "razon_social" => "FERRETERIA/AGUILAR",
                "informacion_contacto" => 72260884,
            ],

            [
                "nombres" => "NELLY ROXANA",
                "apellido_paterno" => "PRADO",
                "apellido_materno" => "ORELLANA",
                "celular" => 65707919,
                "direccion" => "CALLE TUMUSLA N° 266",
                "NIT" => "7240302",
                "razon_social" => "RETENCAR",
                "informacion_contacto" => 65707919,
            ],

            [
                "nombres" => "VLADIMIR WALTER",
                "apellido_paterno" => "ROCHA",
                "apellido_materno" => "SILES",
                "celular" => 72255415,
                "direccion" => "CALLLE INNOMINADA S/N",
                "NIT" => "3521800018",
                "razon_social" => "INDUSTRIA DE LIMPIEZA BOLIVIANA INLIBOL",
                "informacion_contacto" => 4714204,
            ],

            [
                "nombres" => "PASCUAL",
                "apellido_paterno" => "QUISPE",
                "apellido_materno" => "NACHO",
                "celular" => 73212753,
                "direccion" => "AV. JUAN PABLO II N°24 ZONA EX TRANCA  RIO SECO",
                "NIT" => "7162275",
                "razon_social" => "FERTILIZANTE  venta de abono insecticidas urea y fumigadores",
                "informacion_contacto" => 2860196,
            ],

            [
                "nombres" => "NATALIO WILSON",
                "apellido_paterno" => "GODOY",
                "apellido_materno" => "ROJAS",
                "celular" => 72961533,
                "direccion" => "CALLE LOS LIRIOS S\N BARRIO EL PARAISO",
                "NIT" => "4978865",
                "razon_social" => "FAPROLIMPG",
                "informacion_contacto" => 76181268,
            ],

            [
                "nombres" => "JUAN CARLOS",
                "apellido_paterno" => "VALDIVIA",
                "apellido_materno" => "GUTIERREZ",
                "celular" => 0,
                "direccion" => "CALLE BENJAMIN BLANCO N°948",
                "NIT" => "1809031",
                "razon_social" => "PATOS CAR",
                "informacion_contacto" => 4553762,
            ],

            [
                "nombres" => "ISRAEL JAVIER",
                "apellido_paterno" => "PEÑA",
                "apellido_materno" => "VILLARROEL",
                "celular" => 0,
                "direccion" => "AV.INTEGRACION-VILLA TUNARI",
                "NIT" => "7229485015",
                "razon_social" => "COMERCIAL-PEÑAVOL",
                "informacion_contacto" => 77958868,
            ],
            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 72544839,
                "direccion" => "La Paz - Achacachi",
                "NIT" => "1661739",
                "razon_social" => "Planta de lácteos Achacachi",
                "informacion_contacto" => 72544839,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 65765844,
                "direccion" => "Oruro - Challapata",
                "NIT" => "1827649",
                "razon_social" => "Planta de lácteos Challapata",
                "informacion_contacto" => 65765844,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 73267902,
                "direccion" => "Tarija - San Lorenzo",
                "NIT" => "5788479",
                "razon_social" => "Planta de lácteos San Lorenzo",
                "informacion_contacto" => 73267902,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 67055646,
                "direccion" => "Cochabamba - Chapare",
                "NIT" => "5515163",
                "razon_social" => "Planta de lácteos Ivirgarzama",
                "informacion_contacto" => 67055646,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 76211234,
                "direccion" => "Beni - San Andres",
                "NIT" => "5087177010",
                "razon_social" => "Planta de lácteos San Andres",
                "informacion_contacto" => 76211234,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 72705318,
                "direccion" => "Cochabamba - Chapare",
                "NIT" => "1790151",
                "razon_social" => "Planta de Néctar de Villa 14 de Septiembre",
                "informacion_contacto" => 72705318,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 72739546,
                "direccion" => "Cochabamba - Chapare",
                "NIT" => "1038052",
                "razon_social" => "Planta Industrial Valle Sacta",
                "informacion_contacto" => 72739546,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 73507071,
                "direccion" => "La Paz - Caranavi",
                "NIT" => "7136612",
                "razon_social" => "Planta de Néctar Caranavi",
                "informacion_contacto" => 73507071,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 65350812,
                "direccion" => "ZONA\/BARRIO HIPODROMO",
                "NIT" => "1792795",
                "razon_social" => "SICRA S.R.L.",
                "informacion_contacto" => 65350812,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 4246679,
                "direccion" => "AV. LIVERTADOR BOLIVAR N° 1291-Z. CALA CALA",
                "NIT" => "7189125",
                "razon_social" => "MARCOS CONDARCO LOPEZ",
                "informacion_contacto" => 4246679,
            ],

            [
                "nombres" => ".",
                "apellido_paterno" => ".",
                "apellido_materno" => ".",
                "celular" => 70751223,
                "direccion" => "Av. Blanco Galindo Km 1 entre Av. Peru - Edif. Super Mall Oficina 12",
                "NIT" => "1884315",
                "razon_social" => "Alimentación Complementaria Escolar Cochabamba",
                "informacion_contacto" => 70751223,
            ],
            [
                "nombres" => "S.N",
                "apellido_paterno" => "S.A",
                "apellido_materno" => "S.A",
                "celular" => 2490906,
                "direccion" => "ZONA SAN PEDRO  CALLE FELIPE 2DO GUZMAN N° 1578",
                "NIT" => "10678111018",
                "razon_social" => "AGRONAT S.A.",
                "informacion_contacto" => 2490906,
            ],
        ]);
    }
}
